project:
  type: website
  output-dir: docs

website:
  title: "Leila Aburomia"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects 
      - href: resume.qmd
        text: Resume
  page-footer:
    background: light
    left: Leila Aburomia
    right: This website is built with Quarto 
      
    

format:
  html:
    theme: styles.scss
    toc: true
    page-layout: full
    

editor: visual

